# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85f910a8ae38953402180197147e74e7505672593d4cc727af1590fe89ce40ad0805f17a355eeab769bb60032a92f2ae811e220ac72477b595999b65dc7a49af

test:
  secret_key_base: 0e5dca7785f3986732117eded06b58c0202529ec51795cbbea4554a5be7ac9d0513215aa6d71b4538ed09bfe44a9d93a02d5ab669fe37672fab1d7400402ba75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
